# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayWeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('forecast_day_temp', models.IntegerField()),
                ('forecast_night_temp', models.IntegerField()),
            ],
        ),
    ]
