# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayweatherforecast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
