# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20181022_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayweatherforecast',
            name='name',
            field=models.CharField(default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='dayweatherforecast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
